# Generated by Django 3.1.7 on 2021-03-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estaciOmediambiental', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
